spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: https://www.googleapis.com/service_accounts/v1/jwk/securetoken@system.gserviceaccount.com
          issuer-uri: https://securetoken.google.com/c2c-ehailing
  servlet:
    multipart:
      max-file-size: 1MB
      resolve-lazily: true


logging:
  level:
    org:
      springframework:
        security: DEBUG
        web: DEBUG

server:
  port: ${PORT:8080}
  tomcat:
    max-swallow-size: 100MB

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

google:
  maps:
    apiKey: AIzaSyDYP96lRLzzow_gpW-IhI6pg3A6dKE-XCU